dist: xenial

language: php

php:
- 7.2
- 7.3

services:
  - mysql

install:
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:update --force --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script: phpunit --configuration phpunit.xml.dist
